# Site settings
title: Asynchronous inputs
description: "Personal blog of Vladimirs Kotovs - software engineering, open source, and tech"
email: vladimir@kotov.lv
url: "https://blog.kotov.lv"
github_username:  rk13

# Build settings
markdown: kramdown


