# Site settings
title: Asynchronous inputs
email: vladimir@kotov.lv
url: "http://rk13.github.io"
twitter_username: rk13
github_username:  rk13

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "fenced_code_blocks"]


