# Site settings
title: Vladimir''s Notes
email: vladimir@kotov.lv
description: > # this means to ignore newlines until "baseurl:"
  Vladimir''s
baseurl: "/site" # the subpath of your site, e.g. /blog/
url: "http://rk13.github.io" # the base hostname & protocol for your site
twitter_username: rk13
github_username:  rk13

# Build settings
markdown: kramdown
